version: "3"
services:
  api:
    build: .
    ports:
      - 8000:8000
    #env_file:
    #  - ./.env
    environment:
      - DATABASE_HOSTNAME = localhost
      - DATABASE_PORT = 5432
      - DATABASE_PASSWORD = 123456
      - DATABASE_NAME = fastapi
      - DATABASE_USERNAME = postgres
      - SECRET_KEY = khelahobekhelahobekhelahobe
      - ALGORITHM = HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES = 60
      - REDIS_PORT = 6379
      - REDIS_HOST = localhost